#!/bin/bash

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

VERSION=$(cat $ROOT/src/dispenserd/constants.go | grep VERSION | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')

echo "dispenserd version $VERSION"
echo 'building dispenserd...'

GOPATH=$ROOT go build -o $ROOT/bin/dispenserd dispenserd

if [[ $? == 0 ]]; then
    touch $ROOT/data/queue.json
    touch $ROOT/logs/dispenserd.log

    echo 'dispenser built!'
    echo "run in foreground: $ROOT/dispenserd"
    echo "run in background: $ROOT/dispenserd -d"
    echo

       if [[ $* == *--and-run* ]]; then
           $ROOT/dispenserd
       fi
else
    echo 'build failed'
    echo
fi
