#!/bin/bash

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

VERSION="0.0.1"

echo
echo "dispenser version $VERSION by: b"
echo 'building dispenser...'

GOPATH=$ROOT go build -o $ROOT/bin/dispenser dispenser

if [[ $? == 0 ]]; then
    echo 'dispenser built!'
    echo "run in foreground: $ROOT/dispenser"
    echo "run in background: $ROOT/dispenser -d"
    echo

       if [[ $* == *--and-run* ]]; then
           $ROOT/dispenser
       fi
else
    echo 'build failed'
    echo
fi
