#!/bin/bash

ulimit -n 65536
sysctl -w net.ipv4.tcp_tw_reuse=1

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

VERSION=$(cat $ROOT/src/dispenserd/constants.go | grep VERSION | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')

echo "dispenserd version $VERSION"

if [[ ! -f $ROOT/bin/dispenserd ]]; then
    echo "build dispenserd first: $ROOT/build"
else
    if [[ $* == *-d* ]]; then
        echo 'starting dispenserd in background...'
        ROOT=$ROOT nohup $ROOT/bin/dispenserd >> $ROOT/logs/dispenserd.log 2>&1 &
    else
        echo 'starting dispenserd in foreground...'
        ROOT=$ROOT $ROOT/bin/dispenserd
    fi
fi
