#!/bin/bash

# build dispenserd
./build

# zero out queue
echo '' > config/queue.json

# start dispenserd in the background
./dispenserd -d

# give dispenserd a chance to start
echo ''
echo 'sleeping 1 second'
sleep 1

# start tests here
echo ''
echo 'starting tests...'
python tests/test.py
test_status=$(echo $?)

# kill dispenserd
pidof dispenserd | xargs kill -15

exit $test_status
