#!/bin/bash

# build dispenserd
./build

# start dispenserd in the background
./dispenserd -d

# give dispenserd a chance to start
sleep 1

# start tests here
python tests/test.py

# kill dispenserd
pidof dispenserd | xargs kill -15
