#!/bin/bash

while true; do
    RAND=$(( ( RANDOM % 25 )  + 1 ))
    curl http://127.0.0.1:8282/schedule -d "{\"lane\": \"$1\", \"priority\": $RAND, \"message\": \"$RAND test $1 lane\"}"
    echo
done
