#!/bin/bash

while true; do
    curl http://127.0.0.1:8282/test -d "" &
    curl http://127.0.0.1:8282/test -d "" &
    curl http://127.0.0.1:8282/test -d "" &
    curl http://127.0.0.1:8282/test -d "" &
    curl http://127.0.0.1:8282/test -d "" &
    curl http://127.0.0.1:8282/test -d "" &
done
